# Generated by Django 4.0.6 on 2022-07-27 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_developer', models.CharField(max_length=250)),
                ('title_task', models.CharField(max_length=250)),
                ('amount_range_start', models.PositiveIntegerField()),
                ('amount_range_end', models.PositiveIntegerField()),
                ('tags', models.CharField(max_length=250)),
                ('job_description', models.TextField()),
                ('experience', models.CharField(max_length=250)),
                ('job_type', models.CharField(max_length=250)),
                ('enable_remote', models.BooleanField()),
                ('country_location', models.CharField(max_length=250)),
                ('viewed', models.PositiveIntegerField(default=0)),
                ('published_date', models.DateField(auto_now_add=True)),
                ('expire_date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Job',
            },
        ),
        migrations.CreateModel(
            name='Questions_stuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('detail', models.TextField(default='')),
                ('body', tinymce.models.HTMLField()),
                ('viewed', models.PositiveIntegerField()),
                ('tag', models.CharField(max_length=200)),
                ('email_notify', models.BooleanField(default=False)),
                ('whatsapp_notify', models.BooleanField(default=False)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Question',
            },
        ),
        migrations.CreateModel(
            name='Answer_stuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('published_time', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.questions_stuff')),
            ],
            options={
                'verbose_name_plural': 'Answer',
            },
        ),
    ]
