# Generated by Django 4.0.6 on 2022-07-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions_stuff',
            name='detail',
            field=models.CharField(default='', max_length=250),
        ),
    ]
