# Generated by Django 4.0.6 on 2022-07-28 22:36

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_job_work_job_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applied_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('residence', models.CharField(max_length=100)),
                ('current_company', models.CharField(blank=True, max_length=100, null=True)),
                ('resume', models.FileField(upload_to='')),
                ('linkedin_url', models.URLField()),
                ('biography', models.TextField()),
                ('hired', models.BooleanField(default=False)),
                ('interview', models.BooleanField(default=False)),
                ('applied_date', models.DateField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.job_work')),
            ],
            options={
                'verbose_name_plural': 'Job Applied',
            },
        ),
    ]
