# Generated by Django 4.0.6 on 2022-07-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_questions_stuff_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions_stuff',
            name='detail',
            field=models.TextField(default=''),
        ),
    ]
