# Generated by Django 4.0.6 on 2022-07-14 15:30

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_questions_stuff_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions_stuff',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
