# Generated by Django 4.0.6 on 2022-07-30 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_applied_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applied_job',
            name='hired',
        ),
    ]
