# Generated by Django 4.0.6 on 2022-07-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_remove_applied_job_hired'),
    ]

    operations = [
        migrations.AddField(
            model_name='applied_job',
            name='hired_apply',
            field=models.BooleanField(default=False),
        ),
    ]
