# Generated by Django 4.0.6 on 2022-07-21 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_questions_stuff_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer_stuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('published_time', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.questions_stuff')),
            ],
            options={
                'verbose_name_plural': ['Answer'],
            },
        ),
    ]
