# Generated by Django 4.0.6 on 2022-08-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_applied_job_hired_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applied_job',
            name='applied_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
