# Generated by Django 4.0.6 on 2022-07-21 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_answer_stuff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer_stuff',
            options={'verbose_name_plural': 'Answer'},
        ),
        migrations.AlterModelOptions(
            name='questions_stuff',
            options={'verbose_name_plural': 'Question'},
        ),
        migrations.AlterField(
            model_name='answer_stuff',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_question', to='questions.questions_stuff'),
        ),
    ]
