# Generated by Django 4.0.6 on 2022-07-21 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_alter_answer_stuff_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer_stuff',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.questions_stuff'),
        ),
    ]
