# Generated by Django 4.0.6 on 2022-08-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_alter_applied_job_applied_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_work',
            name='job_hired',
            field=models.BooleanField(default=False),
        ),
    ]
