# Generated by Django 4.0.6 on 2022-08-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_job_work_job_hired'),
    ]

    operations = [
        migrations.AddField(
            model_name='applied_job',
            name='rejected_apply',
            field=models.BooleanField(default=False),
        ),
    ]
