# Generated by Django 4.0.6 on 2022-08-01 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_applied_job_rejected_apply'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewApplied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_link', models.URLField()),
                ('interview_date', models.DateField()),
                ('sent_date', models.DateField(auto_now_add=True)),
                ('applied_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.applied_job')),
            ],
            options={
                'verbose_name_plural': 'Interview List',
            },
        ),
    ]
