# Generated by Django 4.0.6 on 2022-08-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_interviewapplied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewapplied',
            name='interview_date',
            field=models.DateTimeField(),
        ),
    ]
