# Generated by Django 4.0.6 on 2022-08-28 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_badge'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_link', models.URLField()),
                ('interview_date', models.DateTimeField()),
                ('published_date', models.DateField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.badge')),
            ],
        ),
    ]
