# Generated by Django 4.0.6 on 2022-09-02 15:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0013_coonectwith'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoonectWith',
            new_name='ConnectWith',
        ),
    ]
