# Generated by Django 4.0.6 on 2022-09-04 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0014_rename_coonectwith_connectwith'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('connect_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.connectwith')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
