# Generated by Django 4.0.6 on 2022-09-10 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_connectstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectwith',
            name='readed_notification',
            field=models.BooleanField(default=False),
        ),
    ]
