# Generated by Django 4.0.6 on 2023-09-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0016_connectwith_readed_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions_stuff',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
