# Generated by Django 4.0.6 on 2023-09-10 21:08

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0017_alter_questions_stuff_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions_stuff',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
