# Generated by Django 4.0.6 on 2024-06-20 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0018_alter_questions_stuff_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions_stuff',
            name='whatsapp_notify',
        ),
    ]
