# Generated by Django 4.0.6 on 2024-06-20 09:59

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0019_remove_questions_stuff_whatsapp_notify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions_stuff',
            name='body',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
