# Generated by Django 4.0.6 on 2024-06-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0021_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='subject',
            field=models.CharField(default='please can you connect with me', max_length=250),
        ),
    ]
