# Generated by Django 4.0.6 on 2024-06-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0022_friendrequest_body_friendrequest_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='readed_request',
            field=models.BooleanField(default=False),
        ),
    ]
