# Generated by Django 4.0.6 on 2022-07-12 21:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_created',
            field=models.DateField(default=datetime.date(2022, 7, 12)),
        ),
    ]
