# Generated by Django 4.0.6 on 2022-07-27 14:21

import datetime
from django.db import migrations, models
from datetime import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2022, 7, 27, 14, 21, 3, 152413, tzinfo=timezone.utc)),
        ),
    ]
