# Generated by Django 4.0.6 on 2022-07-13 11:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_profile_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2022, 7, 13, 11, 18, 58, 497024, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github_link',
            field=models.URLField(blank=True, default='https://github.com/', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='website_link',
            field=models.URLField(blank=True, default='https://www.google.com/', null=True),
        ),
    ]
