# Generated by Django 4.0.6 on 2022-07-13 15:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_profile_date_created_alter_profile_github_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2022, 7, 13, 15, 5, 19, 621578, tzinfo=utc)),
        ),
    ]
