# Generated by Django 4.0.6 on 2022-07-14 15:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_profile_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2022, 7, 14, 15, 24, 3, 387676, tzinfo=utc)),
        ),
    ]
