# Generated by Django 4.0.6 on 2022-08-01 15:57

import datetime
from django.db import migrations, models
from datetime import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_profile_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2022, 8, 1, 15, 57, 52, 42404, tzinfo=timezone.utc)),
        ),
    ]
