# Generated by Django 4.0.6 on 2022-08-02 11:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_profile_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2022, 8, 2, 11, 11, 44, 533824, tzinfo=utc)),
        ),
    ]
