# Generated by Django 4.0.6 on 2022-08-04 16:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_profile_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='badge',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2022, 8, 4, 16, 6, 36, 118267, tzinfo=utc)),
        ),
    ]
