# Generated by Django 4.0.6 on 2023-09-10 21:08

import datetime
from django.db import migrations, models
from datetime import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_alter_profile_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2023, 9, 10, 21, 8, 26, 568881, tzinfo=timezone.utc)),
        ),
    ]
