# Generated by Django 4.0.6 on 2024-06-20 09:49

import datetime
from django.db import migrations, models
from datetime import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0029_alter_profile_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2024, 6, 20, 9, 49, 10, 100519, tzinfo=timezone.utc)),
        ),
    ]
