# Generated by Django 4.0.6 on 2024-06-23 09:11

import datetime
from django.db import migrations, models
from datetime import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0033_alter_profile_about_me_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2024, 6, 23, 9, 10, 51, 480895, tzinfo=timezone.utc)),
        ),
    ]
